name: Mirror Docker Images to GHCR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror images
        run: |
          while read image; do
            echo "==> Processing $image"
            safe_name=$(echo $image | tr '/:' '-')
            docker pull $image
            docker tag $image ghcr.io/${{ github.repository_owner }}/$safe_name
            docker push ghcr.io/${{ github.repository_owner }}/$safe_name
          done < images.txt
